# Perceptron:

# A Very Basic (A)NN (Artificial) Neural Network 
## from scratch in Python

### Basic Parts of This Perceptron: 

1. The input data (X) 
2. The weights (in memory as `weights`)
3. The initial random state of weights
4. The activation function (sigmoid) and its derivative
5. The set number of iterations
6. The calculated weighted sum of inputs
7. The Back-propagation process (going back to check results and weights) 
8. The calculation of error
9. The calculation of adjustments to weights
10. The adjustment of the weights
11. The output

Note: this perceptron would not be able to model a non-linear function (such as an Xor gate)


## These are the changes that will be made to the weights:
adjustments = error * sigmoid_derivative(activated_output)


## This is the probability that an answer will be zero or one:
activated_output = sigmoid(weighted_sum)

error = corrected_output = activated_output

weighted_sum = np.dot(inputs, weights)

In [0]:
# Notes:
# Data-Set(X) & Target(y)

In [0]:
# import libraries
import numpy as np
import pandas as pd

In [0]:
# set a random seed
np.random.seed(42)

In [0]:
# Data as 2 arrays

# X
# numpy array
# analogy: person data
inputs = np.array([
                   [0,0,1],
                   [1,1,1],
                   [1,0,1],
                   [0,1,1]
])

# analogy: blood types
# Y
# list of corrected outputs
correct_outputs = [[0],
                   [1],
                   [1],
                   [0]]

In [0]:
# data as one mask-array for a dataframe
data = np.array([
                   [0,0,0,1],
                   [1,1,1,1],
                   [1,1,0,1],
                   [0,0,1,1]
])

In [0]:
inputs, correct_outputs

(array([[0, 0, 1],
        [1, 1, 1],
        [1, 0, 1],
        [0, 1, 1]]), [[0], [1], [1], [0]])

In [0]:
df = pd.DataFrame(data, columns = ['correct_outputs', 'input1' ,'input2','input3']) 

In [0]:
X = df.iloc[:,1:].values

In [0]:
y = df.iloc[0,:].values

In [0]:
X, y

(array([[0, 0, 1],
        [1, 1, 1],
        [1, 0, 1],
        [0, 1, 1]]), array([0, 0, 0, 1]))

In [0]:
# back propagation: adjusting weights to minimize error
# gradient descent: use the derivative to find the minimum of a function ()

In [0]:
# set the initial random starting weights
weights = 2 * np.random.random((3, 1)) -1

In [0]:
weights

array([[-0.25091976],
       [ 0.90142861],
       [ 0.46398788]])

In [0]:
# this is the activiation function to be used in the NN
# creating a sigmoid function
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

  # caused error:
  #return float(1 / (1 + np.exp(-x)))

In [0]:
def sigmoid_derivative(x):# inspecting/testing
  sx = sigmoid(x)
  return sx * (1 - sx)  

In [0]:
# Steps done before: 
# 1. Randomly initialize weights, in memory as `weights`
# 2. Get input data (X) 
# 3. Get correct_outputs (y) target
# 4. Set activation function (sigmoid) and its derivative

# Steps done here:
# (Forward propagation: through all layers from input to output)
# 5. set number of iterations
# 6. calculate weighted sum of inputs 
# 7. Activate: sigmoid activation function
# (Back propagation: going backwards through the weights/wires)
# 8. Calculating the error
# 9. Calculate adjustents
# 10. apply adjustments to weights

# Each set of wires has its own weights...

# 5 Update our weights X times e.g. 10,000
for iteration in range(10):
    
    # 6 Calculating the weighted sum of inputs
    weighted_sum = np.dot(inputs, weights)
    
    # 7 Activate: sigmoid activation function
    activated_output = sigmoid(weighted_sum)
    
    # 8 Calculating the error
    error = correct_outputs - activated_output
    
    # 9 these are the changes that will later be made to the weights
    adjustments = error * sigmoid_derivative(activated_output)
    
    # 10 Update the Weights: here the weights are changed (happens in the 'wire')
    weights += np.dot(inputs.T, adjustments)
  

In [0]:
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[ 1.29240031]
 [ 0.16483768]
 [-0.50464319]]
Output after training
[[0.39136975]
 [0.7154103 ]
 [0.67140113]
 [0.44169656]]


In [0]:
correct_outputs

[[0], [1], [1], [0]]